spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/asterum
    username: asterum
    password: asterum
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
